# Generated by Django 5.1 on 2024-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shuttle',
            old_name='date',
            new_name='shuttle_date',
        ),
        migrations.RenameField(
            model_name='shuttle',
            old_name='notes',
            new_name='shuttle_notes',
        ),
        migrations.RenameField(
            model_name='shuttle',
            old_name='time',
            new_name='shuttle_time',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='email',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
