# Generated by Django 5.1 on 2024-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0002_rename_date_shuttle_shuttle_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='shuttle_time',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='shuttle_direction',
            field=models.CharField(choices=[('both_ways', 'Both ways'), ('buda_keres', 'Buda - Keres'), ('keres_buda', 'Keres - Buda')], default='both_ways', max_length=20),
            preserve_default=False,
        ),
    ]
