# Generated by Django 5.1 on 2024-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0003_remove_shuttle_shuttle_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_passenger', models.DecimalField(decimal_places=2, default=60.0, max_digits=10)),
            ],
        ),
    ]
