# Generated by Django 5.1 on 2024-10-24 17:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_agent_name_alter_driver_name_alter_staff_name'),
        ('shuttle', '0005_shuttle_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='cc_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='paid_to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.agent'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='paid_to_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.staff'),
        ),
    ]
