# Generated by Django 5.1 on 2024-10-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_agent_name_alter_driver_name_alter_staff_name'),
        ('shuttle', '0007_shuttle_paid_to_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.driver'),
        ),
    ]
