# Generated by Django 5.1 on 2024-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0008_alter_shuttle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
