# Generated by Django 5.1 on 2025-02-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0009_shuttle_is_completed_shuttle_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='paid_to_agent',
        ),
        migrations.RemoveField(
            model_name='shuttle',
            name='paid_to_driver',
        ),
    ]
