# Generated by Django 5.1 on 2025-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0010_remove_shuttle_paid_to_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='customer_number',
            field=models.CharField(max_length=30),
        ),
    ]
