# Generated by Django 5.1 on 2025-05-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_delete_freelancer_delete_freelanceragent'),
        ('shuttle', '0011_alter_shuttle_customer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleDailyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], max_length=3)),
                ('driver_fee_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.driver')),
            ],
        ),
    ]
