# Generated by Django 5.1 on 2025-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0012_shuttledailycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttledailycost',
            name='number_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
