# Generated by Django 5.1 on 2025-05-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0013_shuttledailycost_number_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shuttledailycost',
            name='date',
        ),
        migrations.AddField(
            model_name='shuttledailycost',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shuttle.shuttleday'),
            preserve_default=False,
        ),
    ]
