# Generated by Django 5.1 on 2025-05-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0014_shuttleday_remove_shuttledailycost_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuttles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuttles_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
