# Generated by Django 5.1 on 2025-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0016_shuttle_number_plate_shuttledailycost_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
