# Generated by Django 5.1.7 on 2026-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0018_audit_and_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
