# Generated by Django 5.1 on 2024-08-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_cost_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10)),
                ('driver_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_fee_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10)),
                ('agent_fee', models.CharField(blank=True, choices=[('5%', '5% total'), ('10%', '10% total'), ('50%', '50% profit')], max_length=10, null=True)),
                ('kilometers', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.agent')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
