# Generated by Django 5.1 on 2024-09-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='driver_fee_in_euros',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='fuel_cost_in_euros',
        ),
    ]
