# Generated by Django 5.1 on 2024-09-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_calculation_driver_fee_in_euros_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSettings',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='driver_currency',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='fuel_currency',
        ),
    ]
