# Generated by Django 5.1 on 2024-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_delete_paymentsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='agent_fee',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='kilometers',
        ),
        migrations.AddField(
            model_name='calculation',
            name='agent_fee_percentage',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('50%', '50%')], max_length=5, null=True),
        ),
    ]
