# Generated by Django 5.1 on 2024-09-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_calculation_agent_fee_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.agent'),
        ),
    ]
