# Generated by Django 5.1 on 2024-09-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_calculation_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
