# Generated by Django 5.1 on 2024-09-18 13:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_delete_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_driver_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_agent_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_job_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_wages_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overall_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
    ]
