# Generated by Django 5.1 on 2024-09-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialSummary',
        ),
    ]
