# Generated by Django 5.1 on 2024-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=15)),
                ('job_date', models.DateField()),
                ('job_time', models.TimeField()),
                ('job_description', models.TextField()),
                ('no_of_passengers', models.IntegerField()),
                ('job_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_in_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], max_length=10)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Minivan', 'Minivan'), ('Van', 'Van'), ('Bus', 'Bus')], max_length=10)),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Quick Pay', 'Quick Pay')], max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
        ),
    ]
