# Generated by Django 5.1 on 2024-09-04 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_fee_percentage', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='cc_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
