# Generated by Django 5.1 on 2024-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_paymentsettings_job_cc_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fuel_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10),
        ),
    ]
