# Generated by Django 5.1 on 2024-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_driver_currency_job_driver_fee_job_fuel_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver_fee_in_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fuel_cost_in_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
