# Generated by Django 5.1 on 2024-09-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_price_in_euros_job_job_price_in_euros_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='currency',
            new_name='job_currency',
        ),
    ]
