# Generated by Django 5.1 on 2024-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_currency_job_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='agent_percentage',
            field=models.CharField(choices=[('5', '5% Turnover'), ('10', '10% Turnover'), ('50', '50% Profit')], default='5', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='driver_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='fuel_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='kilometers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Minivan', 'Minivan'), ('Van', 'Van'), ('Bus', 'Bus')], max_length=10, null=True),
        ),
    ]
