# Generated by Django 5.1 on 2024-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_agent_name_alter_job_kilometers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='agent_percentage',
            field=models.DecimalField(blank=True, choices=[(5.0, '5% Turnover'), (10.0, '10% Turnover'), (50.0, '50% Profit')], decimal_places=2, max_digits=5, null=True),
        ),
    ]
