# Generated by Django 5.1 on 2024-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_agent_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='agent_percentage',
            field=models.CharField(blank=True, choices=[('5', '5% Turnover'), ('10', '10% Turnover'), ('50', '50% Profit')], max_length=10, null=True),
        ),
    ]
