# Generated by Django 5.1 on 2024-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_agent_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='kilometers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
