# Generated by Django 5.1 on 2024-09-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_kilometers'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='agent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.agent'),
        ),
    ]
