# Generated by Django 5.1 on 2024-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
