# Generated by Django 5.1 on 2024-09-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_paid',
        ),
    ]
