# Generated by Django 5.1 on 2024-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_job_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
