# Generated by Django 5.1 on 2024-09-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pick_up_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
