# Generated by Django 5.1 on 2024-09-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_drop_off_location_job_flight_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_paid',
        ),
    ]
