# Generated by Django 5.1 on 2024-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_job_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pick_up_location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
