# Generated by Django 5.1 on 2024-09-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_remove_job_fuel_cost_remove_job_fuel_cost_in_euros_and_more'),
        ('people', '0002_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.driver'),
        ),
    ]
