# Generated by Django 5.1 on 2024-09-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_job_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='driver_name',
        ),
    ]
