# Generated by Django 5.1 on 2024-10-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_remove_job_driver_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsettings',
            options={'verbose_name_plural': 'Payment Settings'},
        ),
        migrations.AddField(
            model_name='job',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
