# Generated by Django 5.1 on 2024-10-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_paymentsettings_options_job_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
