# Generated by Django 5.1 on 2024-10-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_job_paid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Quick Pay', 'Quick Pay')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
