# Generated by Django 5.1 on 2024-10-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_remove_job_paid_to_job_paid_to_agent_and_more'),
        ('people', '0005_alter_agent_name_alter_driver_name_alter_staff_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSettings',
        ),
        migrations.AlterField(
            model_name='job',
            name='paid_to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_paid_to_agent', to='people.agent'),
        ),
        migrations.AlterField(
            model_name='job',
            name='paid_to_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_paid_to_driver', to='people.driver'),
        ),
        migrations.AlterField(
            model_name='job',
            name='paid_to_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_paid_to_staff', to='people.staff'),
        ),
    ]
