# Generated by Django 5.1 on 2024-11-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_delete_paymentsettings_alter_job_paid_to_agent_and_more'),
        ('people', '0005_alter_agent_name_alter_driver_name_alter_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], max_length=3)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Quick Pay', 'Quick Pay')], max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobs.job')),
                ('paid_to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.agent')),
                ('paid_to_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.driver')),
                ('paid_to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
