# Generated by Django 5.1 on 2024-11-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_remove_payment_amount_remove_payment_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='job',
            name='paid_to_agent',
        ),
        migrations.RemoveField(
            model_name='job',
            name='paid_to_driver',
        ),
        migrations.RemoveField(
            model_name='job',
            name='paid_to_staff',
        ),
    ]
