# Generated by Django 5.1 on 2024-12-18 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_delete_payment'),
        ('people', '0006_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.freelancer'),
        ),
    ]
