# Generated by Django 5.1 on 2025-03-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_job_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='freelancer',
        ),
    ]
