# Generated by Django 5.1 on 2025-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_remove_job_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer_number',
            field=models.CharField(max_length=30),
        ),
    ]
