# Generated by Django 5.1 on 2025-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_alter_job_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='freelancer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
