# Generated by Django 5.1 on 2025-05-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_job_last_modified_at_job_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
