# Generated by Django 5.1 on 2025-05-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_job_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
