# Generated by Django 5.1 on 2025-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_job_job_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
