# Generated by Django 5.1 on 2025-05-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_job_subtotal'),
        ('people', '0009_delete_freelancer_delete_freelanceragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_driver', to='people.agent'),
        ),
        migrations.AlterField(
            model_name='job',
            name='agent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_agent', to='people.agent'),
        ),
    ]
