# Generated by Django 5.1 on 2025-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_job_driver_agent_alter_job_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Minivan', 'Minivan'), ('Van', 'Van'), ('Bus', 'Bus')], max_length=10, null=True),
        ),
    ]
