# Generated by Django 5.1 on 2025-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_alter_job_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
