# Generated by Django 5.1 on 2026-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_job_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
