services:
  db:
    image: docker.io/bitnami/postgresql:16
    container_name: kt-db
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: $POSTGRES_USER
      POSTGRESQL_PASSWORD: $POSTGRES_PASSWORD
      POSTGRESQL_DATABASE: $POSTGRES_DATABASE
    volumes:
      - postgres-data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  web:
    image: scriptblazer/kt-app:${DOCKER_TAG}
    build:
      context: .
    container_name: kt-app
    restart: unless-stopped
    volumes:
      - static-data:/app/staticfiles
      - ~/kt-app/media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: "curl --fail -s http://127.0.0.1:8000/liveness || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  caddy:
    image: caddy:latest
    container_name: kt-caddy
    restart: unless-stopped
    environment:
      PUBLIC_HOST: $PUBLIC_HOST
    volumes:
      - caddy-data:/data
      - static-data:/app/staticfiles:ro
      - ~/kt-app/media:/app/media:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    healthcheck:
      test: "wget --quiet --spider --timeout=5 --tries=1 https://${PUBLIC_HOST}/liveness || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  pgbackup:
    image: prodrigestivill/postgres-backup-local
    container_name: kt-db-backup
    restart: unless-stopped
    user: postgres:postgres
    volumes:
      - ./pgbackups:/backups
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_EXTRA_OPTS: -Z1 --schema=public --blobs
      SCHEDULE: "@daily"
      BACKUP_ON_START: true
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
    depends_on:
      - db

volumes:
  postgres-data:
  static-data:
  caddy-data: