services:

  web:
    image: scriptblazer/kt-app:${DOCKER_TAG}
    build:
      context: .
    container_name: kt-app
    restart: unless-stopped
    volumes:
      - static-data:/app/staticfiles
      - ./media:/app/media
      - ./django_logs.log:/app/django_logs.log
    env_file:
      - .env
    healthcheck:
      test: "curl --fail -s http://127.0.0.1:8000/liveness || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "7"

  caddy:
    image: caddy:latest
    container_name: kt-caddy
    restart: unless-stopped
    environment:
      PUBLIC_HOST: $PUBLIC_HOST
    volumes:
      - caddy-data:/data
      - static-data:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    healthcheck:
      test: "wget --quiet --spider --timeout=5 --tries=1 https://${PUBLIC_HOST}/liveness || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  pgbackup:
    image: prodrigestivill/postgres-backup-local
    container_name: kt-db-backup
    restart: unless-stopped
    user: postgres:postgres
    volumes:
      - ./pgbackups:/backups
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_EXTRA_OPTS: -Z1 --schema=public --blobs
      SCHEDULE: "@daily"
      BACKUP_ON_START: true
      BACKUP_KEEP_DAYS: 14
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080

volumes:
  static-data:
  caddy-data: