# Generated by Django 5.1.7 on 2026-03-29 18:03

from django.db import migrations, models


def populate_summary(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Shuttle = apps.get_model('shuttle', 'Shuttle')
    HotelBooking = apps.get_model('hotels', 'HotelBooking')
    Summary = apps.get_model('analytics', 'JobAnalyticsSummary')
    Summary.objects.update_or_create(
        pk=1,
        defaults={
            'driving_total': Job.objects.count(),
            'driving_paid': Job.objects.filter(is_paid=True).count(),
            'driving_unpaid': Job.objects.filter(is_paid=False).count(),
            'shuttle_total': Shuttle.objects.count(),
            'shuttle_paid': Shuttle.objects.filter(is_paid=True).count(),
            'shuttle_unpaid': Shuttle.objects.filter(is_paid=False).count(),
            'hotel_total': HotelBooking.objects.count(),
            'hotel_paid': HotelBooking.objects.filter(is_paid=True).count(),
            'hotel_unpaid': HotelBooking.objects.filter(is_paid=False).count(),
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0030_hotelbooking_subtotal'),
        ('jobs', '0049_backfill_job_subtotal_where_null'),
        ('shuttle', '0019_shuttle_is_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_total', models.PositiveIntegerField(default=0)),
                ('driving_paid', models.PositiveIntegerField(default=0)),
                ('driving_unpaid', models.PositiveIntegerField(default=0)),
                ('shuttle_total', models.PositiveIntegerField(default=0)),
                ('shuttle_paid', models.PositiveIntegerField(default=0)),
                ('shuttle_unpaid', models.PositiveIntegerField(default=0)),
                ('hotel_total', models.PositiveIntegerField(default=0)),
                ('hotel_paid', models.PositiveIntegerField(default=0)),
                ('hotel_unpaid', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job analytics summary',
                'verbose_name_plural': 'Job analytics summary',
            },
        ),
        migrations.RunPython(populate_summary, migrations.RunPython.noop),
    ]
