# Generated by Django 5.1 on 2024-10-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_fee_percentage', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
