# Generated by Django 5.1 on 2024-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount_in_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
