# Generated by Django 5.1 on 2025-02-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_payment_paid_to_freelancer_agent'),
        ('shuttle', '0010_remove_shuttle_paid_to_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shuttle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shuttle.shuttle'),
        ),
    ]
