# Generated by Django 5.1 on 2025-02-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_payment_job'),
        ('jobs', '0035_job_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobs.job'),
        ),
    ]
