# Generated by Django 5.1 on 2025-03-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_payment_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_to_freelancer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_to_freelancer_agent',
        ),
    ]
