# Generated by Django 5.1 on 2025-06-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_payment_paid_to_freelancer_and_more'),
        ('hotels', '0023_hotelbooking_booking_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotels.hotelbooking'),
        ),
    ]
