# Generated by Django 5.1.7 on 2026-03-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_audit_and_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='changes',
            field=models.JSONField(blank=True, help_text='List of {label, old, new} for field-level updates.', null=True),
        ),
    ]
