# Generated by Django 5.1 on 2024-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
