# Generated by Django 5.1 on 2024-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_in_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
