# Generated by Django 5.1 on 2024-09-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_amount_in_euros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='expense_amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='amount_in_euros',
            new_name='expense_amount_in_euros',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='currency',
            new_name='expense_currency',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='notes',
            new_name='expense_notes',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='time',
            new_name='expense_time',
        ),
    ]
