# Generated by Django 5.1 on 2024-09-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expense_driver_alter_expense_expense_type'),
        ('people', '0002_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.driver'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('fuel', 'Fuel Bill'), ('wages', 'Wages'), ('repair', 'Car Repair'), ('renovations', 'Office Work'), ('car_wash', 'Car Wash'), ('toll', 'Tolls')], max_length=255),
        ),
    ]
