# Generated by Django 5.1 on 2025-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_images/'),
        ),
    ]
