# Generated by Django 5.1 on 2025-05-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_expense_expense_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expense_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='expenses.expense')),
            ],
        ),
    ]
