# Generated by Django 5.1.7 on 2026-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_expense_created_by_expense_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
