# Generated by Django 5.1 on 2024-10-20 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=30)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('no_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_of_beds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('hotel_tier', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('agent_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.agent')),
                ('bed_types', models.ManyToManyField(to='hotels.bedtype')),
            ],
        ),
    ]
