# Generated by Django 5.1 on 2024-10-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20241020_1301'),
        ('people', '0002_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='price',
            new_name='hotel_price',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='currency',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_price_in_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Quick Pay', 'Quick Pay')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.agent'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='agent_fee',
            field=models.CharField(choices=[('5', '5% Turnover'), ('10', '10% Turnover'), ('50', '50% Profit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_tier',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True),
        ),
    ]
