# Generated by Django 5.1 on 2024-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotelbooking_bed_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='agent_fee',
            field=models.CharField(blank=True, choices=[('5', '5% Turnover'), ('10', '10% Turnover'), ('50', '50% Profit')], max_length=10, null=True),
        ),
    ]
