# Generated by Django 5.1 on 2024-10-20 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotelbooking_agent_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='cc_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
