# Generated by Django 5.1 on 2024-10-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotelbooking_cc_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBookingBedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.bedtype')),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelbooking')),
            ],
        ),
    ]
