# Generated by Django 5.1 on 2024-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_hotelbooking_bed_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotel_currency',
            new_name='hotel_customer_pays_currency',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='customer_pays',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='customer_pays_in_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
