# Generated by Django 5.1 on 2024-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_rename_hotel_currency_hotelbooking_hotel_customer_pays_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='hotel_customer_pays_currency',
            new_name='customer_pays_currency',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_price_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='customer_pays',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
