# Generated by Django 5.1 on 2024-10-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_rename_hotel_customer_pays_currency_hotelbooking_customer_pays_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='customer_pays_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pound Sterling'), ('HUF', 'Hungarian Forint'), ('USD', 'US Dollar')], default='EUR', max_length=10),
        ),
    ]
