# Generated by Django 5.1 on 2024-10-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_alter_hotelbooking_customer_pays_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbookingbedtype',
            name='bed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.bedtype'),
        ),
    ]
