# Generated by Django 5.1 on 2024-10-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_alter_hotelbookingbedtype_bed_type'),
        ('people', '0005_alter_agent_name_alter_driver_name_alter_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='cc_fee',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='paid_to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotelbookings_as_paid_to_agent', to='people.agent'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='paid_to_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotelbookings_as_paid_to_staff', to='people.staff'),
        ),
    ]
