# Generated by Django 5.1 on 2024-10-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_hotelbooking_cc_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
