# Generated by Django 5.1 on 2024-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_hotelbooking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
