# Generated by Django 5.1 on 2024-10-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_hotelbooking_is_completed_hotelbooking_is_paid'),
        ('people', '0005_alter_agent_name_alter_driver_name_alter_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='paid_to_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_paid_to_agent', to='people.agent'),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='paid_to_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_paid_to_staff', to='people.staff'),
        ),
    ]
