# Generated by Django 5.1 on 2024-12-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_hotelbooking_paid_to_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='agent_fee',
            new_name='agent_percentage',
        ),
    ]
