# Generated by Django 5.1 on 2025-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_rename_agent_fee_hotelbooking_agent_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer'), ('Quick Pay', 'Quick Pay')], max_length=50, null=True),
        ),
    ]
