# Generated by Django 5.1 on 2025-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_alter_hotelbooking_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
