# Generated by Django 5.1 on 2025-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_hotelbooking_hotel_branch_hotelbooking_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(default='Hotel', max_length=255),
            preserve_default=False,
        ),
    ]
