# Generated by Django 5.1 on 2025-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_alter_hotelbooking_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
