# Generated by Django 5.1 on 2025-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_hotelbooking_booking_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
