# Generated by Django 5.1 on 2025-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_hotelbooking_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
