# Generated by Django 5.1 on 2025-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_hotelbooking_is_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='freelancer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
