# Generated by Django 5.1 on 2025-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_hotelbooking_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='freelancer',
        ),
    ]
