# Generated by Django 5.1.7 on 2026-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0028_hotelbooking_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
