# Generated by Django 5.1.7 on 2026-03-29 17:02

from decimal import Decimal

from django.db import migrations, models


def backfill_subtotal(apps, schema_editor):
    HotelBooking = apps.get_model('hotels', 'HotelBooking')
    for row in HotelBooking.objects.all().only(
        'pk', 'customer_pays_in_euros', 'agent_percentage'
    ):
        customer = row.customer_pays_in_euros or Decimal('0')
        driver_fee = Decimal('0')
        ap = row.agent_percentage
        if ap == '5':
            agent_fee = (customer * Decimal('0.05')).quantize(Decimal('0.01'))
        elif ap == '10':
            agent_fee = (customer * Decimal('0.10')).quantize(Decimal('0.01'))
        elif ap == '50':
            agent_fee = (
                ((customer - driver_fee) * Decimal('0.50')).quantize(Decimal('0.01'))
                if customer > Decimal('0')
                else Decimal('0')
            )
        else:
            agent_fee = Decimal('0')
        sub = (customer - agent_fee).quantize(Decimal('0.01'))
        HotelBooking.objects.filter(pk=row.pk).update(subtotal=sub)


def backfill_subtotal_reverse(apps, schema_editor):
    HotelBooking = apps.get_model('hotels', 'HotelBooking')
    HotelBooking.objects.all().update(subtotal=None)


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_audit_and_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(backfill_subtotal, backfill_subtotal_reverse),
    ]
