# Generated by Django 5.1 on 2024-10-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_office'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='Staff',
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
