# Generated by Django 5.1 on 2024-12-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_freelancer_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer_agent',
            new_name='FreelancerAgent',
        ),
    ]
