# Generated by Django 5.1 on 2025-03-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_payment_paid_to_freelancer_and_more'),
        ('jobs', '0036_remove_job_freelancer'),
        ('people', '0008_rename_freelancer_agent_freelanceragent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='FreelancerAgent',
        ),
    ]
